### ISSUE TITLE
request to translate into Indonesian

### ISSUE THREAD

**Issue by mohdhaekal** [MisterY/gnucash-portfolio#51]
Hello, sir
may i join here. because I want to translate into Indonesian.
so that people Indonesia country easier when reading it

**Comment by MisterY** [comment]
Hi, @mohdhaekal. Thanks for your interest. This is still a very early version but you would be welcome to join.

Currently there is no mechanism nor support for multiple languages. You are free to suggest a not-too-painful way for translating the content first. Hope that will not be too much of a drag on development of other features.
Since this is still a very early version, the content changes a lot, so providing translations might not yet make much sense. It would get deprecated by the day. 
Perhaps users could use Google Translate to translate the whole page on the fly, as as easier solution?
